### ISSUE TITLE
Windows 10: File /npm/node_modules/devtool/index.html not found

### ISSUE THREAD

**Issue by F3n67u** [Jam3/devtool#107]
When I open devtool in win10, devtool console show:
`npm/node_modules/devtool/index.html  Failed to load resource: net::ERR_FILE_NOT_FOUND`

It is very annoying. Could you add a `index.html` file to you project root path?

**Comment by eorroe** [comment]
I'm having the same problem but with `\npm\node_modules\devtool\bin\index.js` file, devtool used to work, and now I can't debug at all without it
