### ISSUE TITLE
add support async/await

### ISSUE THREAD

**Issue by phra** [Jam3/devtool#118]
hi,

currently devtool doesn't support for async/await already available in latest chromium and nodejs.
i'm creating this ticket to track the status of this feature. :rocket:

**Comment by w05163** [comment]
find devtool folder and update electron to version 1.7.2 can solve this problem for temporarily

**Comment by phra** [comment]
@w05163 it's not needed. now there is the new debugging protocol and you can use the "--inspect" flag and attach your chrome to it. closing this issue.
https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

**Comment by hutber** [comment]
I was actually going to say the same thing, the only thing that is missing is the network tab that I could see.
