### ISSUE TITLE
Crashes on key press in DevTools' console

### ISSUE THREAD

**Issue by simov** [Jam3/devtool#14]
I'm setting some breakpoints, at some point I'm deciding to write something in the console. On first key press the devtool window closes without any error message shown.

Ubuntu 15.04

**Comment by saitodisse** [comment]
same here: `Ubuntu 14.04`
no errors, just close

**Comment by mattdesl** [comment]
seems like newest Electron fixes this.
https://github.com/Jam3/devtool/issues/15#issuecomment-174022577

@saitodisse update like so:

```sh
npm install devtool -g
```
