### ISSUE TITLE
Clicking on Global crashes the tool

### ISSUE THREAD

**Issue by simov** [Jam3/devtool#15]
![global](https://cloud.githubusercontent.com/assets/1694112/12463422/0ca470f2-bfcc-11e5-9bca-fb9ef0339b7b.png)

In much the same was as in https://github.com/Jam3/devtool/issues/14 the devtool window just closes.

Ubuntu 15.04

**Comment by mattdesl** [comment]
Can't reproduce either issue on OSX – sounds like it may be an Electron issue. :disappointed:

**Comment by simov** [comment]
doh you just have to love this type of user experience

**Comment by MCluck90** [comment]
Must be a Linux problem. Can't reproduce it on Windows 10.

**Comment by mattdesl** [comment]
@simov I just updated Electron which may help with this issue. Can you let me know if it's still crashing?

**Comment by mattdesl** [comment]
p.s. To update:

```sh
npm i devtool -g
```

**Comment by simov** [comment]
The global button seems to be working as well as the console :+1:

**Comment by mattdesl** [comment]
:tada:
