### ISSUE TITLE
devtool can not support:  run as debug

### ISSUE THREAD

**Issue by rockcoder23** [Jam3/devtool#19]
I have some codes like below: 

```js
//filename: sum.js
function sum(a, b) {
var result = a + b;  // line 3
return result;
}
sum(1, 2);
```
I want stop the code at line 3. then I run `devtool sum.js`,  it run done without any control.

most debug tools can add breakpoints to sum.js first, then I can select this file run as debug mode, so in this way I can debug the code easy.

**Comment by CMTegner** [comment]
It's also worth mentioning that `debugger` statements aren't working as expected until the app is fully launched, leading me to think that the source is executed before the debugger is attached.

**Comment by CMTegner** [comment]
Must have missed this during my first read-through of the readme:

> When the DevTools window first opens, you may need to reload the browser for source maps and debugging to work correctly (related: electron#2379)

**Comment by mattdesl** [comment]
> most debug tools can add breakpoints to sum.js first, then I can select this file run as debug mode, so in this way I can debug the code easy.

Electron doesn't (yet) provide a way to inject break points like this.

Right now you will need to run the DevTool and then reload (Cmd + R or Ctrl + R) before the debugger and source maps work nicely.

> It's also worth mentioning that debugger statements aren't working as expected until the app is fully launched, leading me to think that the source is executed before the debugger is attached.

@s-a Did you also have this issue in `iron-node`? If so how did you get around it?

**Comment by s-a** [comment]
In ironNode I am waiting for DevTools opened event. After that I launch a debug session.  
https://github.com/s-a/iron-node/blob/54fd8aa1cfb01d970ffd6d625cf81247b4f7510c/app/index.js#L100

**Comment by mattdesl** [comment]
Thanks @s-a – it seems obvious now. :smile:

@CMTegner Your issue should be fixed; you no longer need to reload the page for `debugger` statement or source maps to work.

**Comment by CMTegner** [comment]
Just gave 1.3.1 a quick test, and during my – very limited – testing `debugger` statements seem to be working as expected. Great work @mattdesl!

**Comment by mattdesl** [comment]
I just fixed up the previous commit so it is a bit more robust – the debugger should now be active by the time the app loads.

I also added a `--break` option to the CLI in `1.4.0` which injects a hidden debugger statement into the first line of your entry file, allowing it to "break on first run" like with `node-inspector`. This is particularly useful if you need to debug something that you can't just reload (i.e. the script depends on `process.stdin` which is only sent once).

Hopefully this issue is all cleared up, now. :smile:

**Comment by rockcoder23** [comment]
yep~ sounds very nice! thanks a lot~~ :smile: :+1:
