### ISSUE TITLE
functions lose 'use strict' scope, so 'const', 'let', etc. don't work

### ISSUE THREAD

**Issue by wellsjo** [Jam3/devtool#20]
When using `let` or `const` inside a function, I get this error
>Error compiling module: /Users/wells/src/heatmap-data/organize-orientations.js
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

To reproduce:
```javascript
'use strict'

const foo = 'bar';  // works fine

function bax() {
  let foo2 = 'bar'; // throws error
}

function bax2() {
  'use strict'
  let foo2 = 'bar'; // works fine
}
```

**Comment by mattdesl** [comment]
This should be fixed in latest since we updated Electron. To update:

```sh
npm install devtool -g
```

:smile:
