### ISSUE TITLE
Why some nodejs apis can be debug step in, some can not?

### ISSUE THREAD

**Issue by rockcoder23** [Jam3/devtool#21]
for example， `os.cpus()` can not step in ,but `res.end()` can。
```js
'use strict'
var http = require('http');
var os = require('os');
http.createServer(function(req, res){
 os.cpus();               // can not step in
 res.end('hello devtool');  // can step in
})
.listen(8080, function(){
console.log('server start...');
})
```
at last， can devtool support debug in the c++ codes? like build in modules of nodejs and the libuv?
thks~

**Comment by mattdesl** [comment]
My guess is that Chrome can only step into JS sources, and 'os' probably contains a bunch of native c/c++ code.

**Comment by rockcoder23** [comment]
Thks @mattdesl. Maybe you are right~ 
According to the nodejs sources, `os.js`  has some codes like this: 
```js
const binding = process.binding('os');

//some codes.....

exports.cpus = binding.getCPUs;   // here

//some codes...

exports.platform = function() {
  return process.platform;   // this line
};
```
The function(`os.cpus()`) contains a bunch of native c/c++ code indeed. And  I try to debug another function(`os.platform`), devtool can reach the function platform of os.js, but only the function platform, no more deep.

**Comment by mattdesl** [comment]
:+1: Seems like that's the case. Going to close.
