### ISSUE TITLE
node commandline options

### ISSUE THREAD

**Issue by lgersman** [Jam3/devtool#26]
Hello, 

i have some nodejs apps requiring to be started with special node options (mostly for enabling es6 features of nodejs). 

An example : 
````
node --harmony --harmony-destructuring --harmony-modules --harmony-default-parameters myapp.js
````

How can it be done in devtool ? 

Kind regards,

Lars

**Comment by mattdesl** [comment]
There is no mechanism in electron to pass node CLI args to v8. But we can take the same approach as iron-node and use a config file for V8/Chromium switches. See issue #9.

**Comment by lgersman** [comment]
:+1:

**Comment by mattdesl** [comment]
Ok, so this already works out of the box. It is needed for certain features which need to be set before V8 initializes, like proxies (from what I understand):

```sh
devtool src/index.js --js-flags="--harmony-proxies"
```

Also added `rc` config with details here, which can be used for V8 flags:
https://github.com/Jam3/devtool/blob/master/docs/rc-config.md

You can update to `1.6.0` for rc features.

```sh
# to update...
npm install devtool -g
```

**Comment by lgersman** [comment]
+1!!!!!
