### ISSUE TITLE
Workspace support?

### ISSUE THREAD

**Issue by remy** [Jam3/devtool#27]
I've been using devtool recently for better visual node debugging and I wanted to ask whether workspaces would be on the radar? Being able to edit live and save instantly to disk would be a huge bonus.

iron-node supports workspaces, but it tries to do it automatically and loads it from `path.dirname(__filename)` which tends to limit to only one directory (a problem if I'm running from `/bin` and my code is in `/lib`).

I've also noticed that the devtool breakpoints are saved on re-run (useful), so it would be useful if workspaces was added if the config could be saved too?

**Comment by mattdesl** [comment]
Thanks for testing. Sadly we are blocked on Electron for this. 
https://github.com/Jam3/devtool/issues/7

Iron-node's workspaces have the same limitation. Live edit isn't reflected in the in-memory files so it becomes a pretty clunky experience while debugging. For this reason I've chosen not to implement until Electron exposes more features for this.
