### ISSUE TITLE
Wrong node version

### ISSUE THREAD

**Issue by jwhitmarsh** [Jam3/devtool#34]
I'm using LTS (4.2.6) but running `process.version` in devtool returns 5.1.1.

Is there anyway to set the version it uses?

**Comment by mattdesl** [comment]
I don't think there's really much we can do about that. Electron chooses the versions, so you could fork/clone `devtool` and install a different version of Electron, but at a certain point you will run up against conflicts with breaking Electron changes or crucial bug fixes for devtool.

**Comment by mattdesl** [comment]
Closing since this isn't a bug with devtool.
