### ISSUE TITLE
Chrome Devtool Plugin support

### ISSUE THREAD

**Issue by iamdustan** [Jam3/devtool#35]
Does this or can this support chrome devtool plugins? I honestly have no idea where to look or how to see if it is already possible or how it can be implemented.

**Comment by mattdesl** [comment]
Yup, sorta. If the extension works with Electron it will also work with `devtool`.

https://github.com/Jam3/devtool/blob/master/docs/rc-config.md

If you find some extensions that work nicely, feel free to PR and add them to the list there.

**Comment by iamdustan** [comment]
Cool. Thanks for the links on that.

My motivation is in an attempt to get [react-devtools](https://github.com/facebook/react-devtools) working in there so I can use it for [react-hardware](https://github.com/iamdustan/react-hardware/tree/rewrite).

I tried using it from both the already installed chrome plugin (`"~/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/{version}"`) and cloning and building the project from source to no avail.

If you have any other tips/docs I’d keep digging. Either way closing this issue for now since the hooks are all there. Thank you!
