### ISSUE TITLE
Add electron version to --version, -v output 

### ISSUE THREAD

**Issue by MadLittleMods** [Jam3/devtool#52]
Add electron version `process.version` to `devtool -v` output for easy reference on what electron version to recompile native addons to ([see gotchas](https://github.com/Jam3/devtool#gotchas))

https://github.com/Jam3/devtool/blob/82c6c558b000dc5d38ca7ab140ba23633892c319/server.js#L26

**Comment by zzarcon** [comment]
Done in https://github.com/Jam3/devtool/pull/55
