### ISSUE TITLE
require('debug') messages not showing in devtool console?

### ISSUE THREAD

**Issue by coodoo** [Jam3/devtool#66]
Just wondering is there any way to make [debug](https://github.com/visionmedia/debug) messages showing up within devtool console, instead of terminal? Thanks.

**Comment by mattdesl** [comment]
It may be possible with a different debug library, one that is more "universal" and works seamlessly in both node/browser.

To get `debug` working in the browser you either have to:

- Use `require('debug/browser')`
- Or, use `devtool --browser-field`, but this will affect all other requires

You also need to enable [browser support](https://github.com/visionmedia/debug#browser-support).

**Comment by coodoo** [comment]
Thanks for the info, as a side note, any suggested universal debug library?
