### ISSUE TITLE
Support `--` full stop CLI args

### ISSUE THREAD

**Issue by mattdesl** [Jam3/devtool#8]
As more flags are added to `devtool` CLI, they will start to pollute the flags that a program may want to use for whatever reason.

Maybe when a full stop is present, `--`, anything after that will be present in the `process.argv` for the running program, and the other flags (e.g. `--browser-field`) will be stripped.

```sh
devtool app.js --browser-field -- -q -b --blah
```

**Comment by halhenke** [comment]
Sounds good - is consistent with the way other tools solve this problem :+1:

**Comment by mattdesl** [comment]
This is now supported in `1.2.1`, it also cleans up gulp/grunt debugging. :beers:

**Comment by halhenke** [comment]
Awesome!
